// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MauiApp2.Model.CourseModel;
//
//    var course = Course.FromJson(jsonString);

namespace MauiApp2.Model.CourseModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.Text.Json.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Course
    {
        [JsonPropertyName("subjectId")]
        public string SubjectId { get; set; }

        [JsonPropertyName("subjectName")]
        public string SubjectName { get; set; }
    }

    public partial class Course
    {
        public static List<Course> FromJson(string json) => JsonConvert.DeserializeObject<List<Course>>(json, MauiApp2.Model.CourseModel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Course> self) => JsonConvert.SerializeObject(self, MauiApp2.Model.CourseModel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
