// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MauiApp2.Model.RegisterCourseModel;
//
//    var registerCourseModel = RegisterCourseModel.FromJson(jsonString);

namespace MauiApp2.Model.RegisterCourseModel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RegisterCourseModel
    {
        [JsonProperty("studentId")]
        public string StudentId { get; set; }

        [JsonProperty("registeredCourses")]
        public List<RegisteredCourse> RegisteredCourses { get; set; }
    }

    public partial class RegisteredCourse
    {
        [JsonProperty("term")]
        public string Term { get; set; }

        [JsonProperty("year")]
        public String Year { get; set; }

        [JsonProperty("subjects")]
        public List<Subject> Subjects { get; set; }
    }

    public partial class Subject
    {
        [JsonProperty("subjectId")]
        public string SubjectId { get; set; }

        [JsonProperty("subjectName")]
        public string SubjectName { get; set; }
    }

    public partial class RegisterCourseModel
    {
        public static List<RegisterCourseModel> FromJson(string json) => JsonConvert.DeserializeObject<List<RegisterCourseModel>>(json, MauiApp2.Model.RegisterCourseModel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<RegisterCourseModel> self) => JsonConvert.SerializeObject(self, MauiApp2.Model.RegisterCourseModel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
